server:
  port: 8080
  error:
    include-message: always
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/his_inpatient?options=-c%20client_encoding%3DUTF8
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: file:sql/init.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  messages:
    encoding: UTF-8

logging:
  charset:
    console: UTF-8
    file: UTF-8

mybatis:
  configuration:
    map-underscore-to-camel-case: true
